<?php
$escape = $this->plugin('escapeHtml');
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'item resource browse');
$siteItemSets = $site->siteItemSets();

$query = $this->params()->fromQuery();
$itemSetShow = isset($itemSet);
if ($itemSetShow):
    $this->htmlElement('body')->appendAttribute('class', 'item-set');
    $query['item_set_id'] = $itemSet->id();
endif;
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');
?>


<?php if ($itemSetShow): ?>
<?php echo $this->pageTitle($itemSet->displayTitle(), 2); ?>
<h3><?php echo $translate('Item set'); ?></h3>
<div class="metadata">
    <?php echo $itemSet->displayValues(); ?>
</div>
<div class="item-set-items">
    <?php echo '<h3>' . $escape($translate('Items')) . '</h3>'; ?>
    <?php else: ?>
        <?php echo $this->pageTitle($translate('Items'), 2); ?>
    <?php endif; ?>

    <?php echo $this->searchFilters(); ?>

    <div class="browse-controls">
        <?php echo $this->pagination();?>
        <a href="<?php echo str_replace("item", "", $_SERVER["SCRIPT_URI"]) ?>search?<?php echo $_SERVER['QUERY_STRING']?>"><?php echo $translate('Advanced search')?></a>
    </div>

    <?php $this->trigger('view.browse.before'); ?>
    <div class="resource-list">
        <?php
        foreach ($items as $item):
            $heading = $headingTerm ? $item->value($headingTerm, ['default' => $translate('[Untitled]')]) : $item->displayTitle();
            $body = $bodyTerm ? $item->value($bodyTerm) : $item->displayDescription();
            ?>
            <div class="item resource">
                <div class="item-meta">
                    <h4><?php echo $item->link($heading); ?></h4>
                </div>
                <?php
                $itemMedia = $item->media();
                $thumbnail = $this->thumbnail($item, 'medium');
                foreach ($itemMedia as $media):


                    if (strpos($media->mediaType(), 'text/html') !== false) :
                        $thumbnail = '<img id="'.$item->id().'" src="'.$this->assetUrl('img/link.png').'" style="width: 150px;">';
                        $url = $media->source();

                    endif;
                endforeach;
                if (empty($thumbnail)) :
                    $abstract = "<p>".substr($item->value('dcterms:abstract'),0,120) . "...</p>";
                    $thumbnail = $abstract;
                endif;

                echo $item->linkRaw($thumbnail, null, ['class' => 'item-thumbnail']);
                ?>
            </div>
        <?php endforeach; ?>
    </div>
    <?php $this->trigger('view.browse.after'); ?>
    <div class="browse-controls">
        <?php echo $this->pagination(); ?>
    </div>
