<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
?>

<?php echo $this->pageTitle($item->displayTitle(), 2); ?>
<h3><?php echo $translate('Item'); ?></h3>
<?php $this->trigger('view.show.before'); ?>
<?php if ($embedMedia && $itemMedia): ?>
    <div class="media-embeds">
    <?php foreach ($itemMedia as $media):
        echo $media->render();
    endforeach;
    ?>
    </div>
<?php endif; ?>
<div class="propgrid">
    <?php if (!$embedMedia && $itemMedia): ?>
        <div class="media-list">
            <div class="values">
                <?php foreach ($itemMedia as $media):
                    if (strpos($media->mediaType(), 'text') !== false) {
                        $url = $media->source();
                        if (strpos($url, 'youtube') !== false) {?>
                            <iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/<?php echo substr($url, strpos($url, 'v=')+2,11)?>" style="max-width: 100%;" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                        <?php } elseif (strpos($url, 'twitter') !== false) {?>
                            <div id="tweet" tweetID="<?php echo substr($url, strpos($url, 'status/')+7)?>"></div>
                            <?php
                            $this->headScript()->appendFile('https://platform.twitter.com/widgets.js');
                            $this->headScript()->appendFile($this->assetUrl('js/embed_tweet.js'));
                        } else { ?>
                            <div id="link-content"><a href="<?php echo $url ?>" target="_blank"><?php echo $url ?></a> </div>
                            <script>
                                $.ajax({
                                    url: "https://api.linkpreview.net/?key=2551cec81a33f40ac6c9cfe92f221611&q=<?php echo $url ?>",
                                    type: "GET",
                                    contentType: "application/json",
                                    success: function(result){
                                        let img = "";
                                        if (result.image) {
                                            img = `<img src="${ result.image }">`;
                                        }
                                        document.getElementById("link-content").innerHTML = `<a href="${ result.url }" target="_blank">${ img }<div class="link-content"><h4> ${ result.title } </h4><p> ${ result.description.substr(0,180) }...</p></div></a>`
                                    }
                                });
                            </script>
                        <?php }
                    } else {
                        echo $media->linkPretty('large');
                    }

                endforeach; ?>
            </div>
        </div>
    <?php endif; ?>
    <div class="properties">
    <?php echo $item->displayValues(); ?>
    <div class="property">
        <?php $itemSets = $item->itemSets(); ?>
        <?php if (count($itemSets) > 0): ?>
        <h4><?php echo $translate('Item sets'); ?></h4>
        <div class="values">
            <?php foreach ($itemSets as $itemSet): ?>
            <div class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
            <?php endforeach; ?>
        </div>
        <?php endif; ?>
    </div>

    </div>

</div>

<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 25, $property);
?>
<?php if ($subjectValues): ?>
<div id="item-linked">
    <h3><?php echo $translate('Linked resources'); ?></h3>
    <?php echo $subjectValues; ?>
</div>
<?php endif; ?>

<?php $this->trigger('view.show.after'); ?>


<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery(document).trigger('enhance.tablesaw');        
    });
</script>
