<?php
$translate = $this->plugin('translate');
?>
<div class="preview-block">

<?php if ($this->heading): ?>
<h2><?php echo $this->heading; ?></h2>
<?php endif; ?>
<div class="resource-list preview">
<?php
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');
foreach ($this->resources as $resource):
    $heading = $headingTerm ? $resource->value($headingTerm, ['default' => $translate('[Untitled]')]) : $resource->displayTitle();
    $body = $bodyTerm ? $resource->value($bodyTerm) : $resource->displayDescription();
?>
    <div class="<?php echo $this->resourceType; ?> resource">
        <h4><?php echo $resource->link($heading); ?></h4>
        <?php
        $itemMedia = $resource->media();
        foreach ($itemMedia as $media):
            $thumbnail = $this->thumbnail($resource, 'medium');

            if (strpos($media->mediaType(), 'text/html') !== false) :
                $thumbnail = '<img id="'.$resource->id().'" src="'.$this->assetUrl('img/link.png').'" style="width: 150px;">';
            endif;


            if (empty($thumbnail)){
                $abstract = "<p>".substr($resource->value('dcterms:abstract'),0,80) . "...</p>";
                $thumbnail = $abstract;
            }
            echo $resource->linkRaw($thumbnail, null, ['class' => 'item-thumbnail']);
        endforeach; ?>
    </div>
<?php endforeach; ?>
</div>

<?php
if ($this->linkText):
    echo $this->hyperlink($this->linkText, $this->url(
        'site/resource', ['controller' => $this->resourceType, 'action' => 'browse'], ['query' => $this->query], true
    ));
endif;
?>

</div>
